### ISSUE TITLE
Something is wrong with encoding

### ISSUE THREAD

**Issue by marcvs** [KIT-SCC/aarc-g002-entitlement#11]
Tox fails on some machines. The cause might be that the failing environment uses locale C.UTF-8, while the working one had en_US.UTF-8.

The reporter sent us this trace:
```
Collecting aarc-g002-entitlement>=0.1.5
   Downloading aarc_g002_entitlement-0.1.7.tar.gz (20 kB)
     ERROR: Command errored out with exit status 1:
      command:
/tmp/workspace/EP-OC-org_conex-generator_master/.tox/shared/bin/python3.6 -c
'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
egg_info --egg-base
/tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/pip-egg-info
          cwd: /tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/
     Complete output (24 lines):
     ERROR:root:Error parsing
     Traceback (most recent call last):
       File "/tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/.eggs/pbr-5.4.5-py3.6.egg/pbr/core.py",
line 96, in pbr
         attrs = util.cfg_to_args(path, dist.script_args)
       File "/tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/.eggs/pbr-5.4.5-py3.6.egg/pbr/util.py",
line 271, in cfg_to_args
         pbr.hooks.setup_hook(config)
       File "/tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/.eggs/pbr-5.4.5-py3.6.egg/pbr/hooks/__init__.py",
line 25, in setup_hook
         metadata_config.run()
       File "/tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/.eggs/pbr-5.4.5-py3.6.egg/pbr/hooks/base.py",
line 27, in run
         self.hook()
       File "/tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/.eggs/pbr-5.4.5-py3.6.egg/pbr/hooks/metadata.py",
line 26, in hook
         self.config['name'], self.config.get('version', None))
       File "/tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/.eggs/pbr-5.4.5-py3.6.egg/pbr/packaging.py",
line 858, in get_version
         version = _get_version_from_pkg_metadata(package_name)
       File "/tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/.eggs/pbr-5.4.5-py3.6.egg/pbr/packaging.py",
line 826, in _get_version_from_pkg_metadata
         pkg_metadata = email.message_from_file(pkg_metadata_file)
       File "/usr/lib/python3.6/email/__init__.py", line 54, in
message_from_file
         return Parser(*args, **kws).parse(fp)
       File "/usr/lib/python3.6/email/parser.py", line 54, in parse
         data = fp.read(8192)
       File "/tmp/workspace/EP-OC-org_conex-generator_master/.tox/shared/lib/python3.6/encodings/ascii.py",
line 26, in decode
         return codecs.ascii_decode(input, self.errors)[0]
     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position
2316: ordinal not in range(128)
     error in setup command: Error parsing
/tmp/pip-install-q7ahxlj8/aarc-g002-entitlement/setup.cfg:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2316:
ordinal not in range(128)
     ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info
Check the logs for full command output.
>
ERROR: could not install deps
[-r/tmp/workspace/EP-OC-org_conex-generator_master/requirements.txt,
-r/tmp/workspace/EP-OC-org_conex-generator_master/test-requirements.txt]; v
= InvocationError('/tmp/workspace/EP-OC-org_conex-generator_master/.tox/shared/bin/pip
install -U
-r/tmp/workspace/EP-OC-org_conex-generator_master/requirements.txt
-r/tmp/workspace/EP-OC-org_conex-generator_master/test-requirements.txt (see
/tmp/workspace/EP-OC-org_conex-generator_master/.tox/shared/log/pep8-1.log)',
1)
```

**Comment by marcvs** [comment]
Can't reproduce
